package main

import "net/http"

func (a *App) v1DocsHandler(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, map[string]any{
		"version":  "1",
		"title":    "Eduardo OS external API",
		"baseHint": "https://eduardoos.com (or your deployed origin); all paths are absolute from that host",
		"auth": map[string]any{
			"header":    "Authorization",
			"scheme":    "Bearer",
			"keyPrefix": apiKeyPrefix,
			"notes":     "Create keys only in the signed-in UI after subscribing to api. Secret shown once. Never create/revoke keys from external API clients.",
		},
		"rateLimit": map[string]any{
			"requestsPerMinute": apiKeyRatePerMin,
			"onExceed":          "HTTP 429 with Retry-After",
		},
		"entitlements": map[string]any{
			"apiProduct": productAPI,
			"notes":      "Non-admin: active api entitlement plus the product (ereport, homescool, or epam). Legacy entitlement id pamphlet counts as epam. Writes only for resources owned by the key owner.",
		},
		"ownerSafe": "Display metadata only (lowercase email with @ replaced by _at_). Filesystem ownership uses immutable ownerUserId from the API key owner.",
		"keyPolicy": "API keys are created, listed, and revoked only in the Eduardo OS UI. Key lifecycle is not part of the external API.",
		"skills": map[string]any{
			"ereport":   "https://github.com/EduardoOsteicoechea/eduardoos-ereport-connector — clone as .ereport/ sidecar.",
			"homescool": "https://github.com/EduardoOsteicoechea/eduardoos-eoschool-connector — clone as .eoschool/ sidecar. Mirror: https://eduardoos.com/skills/eoschool/",
			"epam":      "https://github.com/EduardoOsteicoechea/epam — clone as .epam/ sidecar. Mirror: https://eduardoos.com/skills/epam/",
		},
		"skill": "https://github.com/EduardoOsteicoechea/eduardoos-ereport-connector — clone as .ereport/. Homescool: eduardoos-eoschool-connector as .eoschool/. EPAM: https://github.com/EduardoOsteicoechea/epam as .epam/.",
		"agentGuidance": "1) Require EDUARDOOS_API_KEY. 2) ALWAYS GET /api/v1/docs first. 3a) eReport: access → orgs → reports → GET → POST append/replace, or use granular section/group/item POST/PATCH for the web connector. For a **site** connector, point EDUARDOOS_ORG_ID/EDUARDOOS_REPORT_ID at the owner's single website_registration report (hub purpose); the site UI Connector locks to that binding while the API still allows all owned reports. 3b) Homescool materials: access → list → POST with confirmOverwrite. 3c) EPAM: access → POST /api/v1/epam/epams with the pamphlet/.epam document (auto-publishes to /articles when the key owner is the public articles publisher). PUT requires confirmOverwrite:true. 4) Always print viewUrl and articleUrl after write. 5) Never invent endpoints — use this catalog. 6) Web embed: https://eduardoos.com/ereport/embed.js → mount({ orgId, reportId, menuSelector }) (session + subscription; no API key). 7) eduardoos.com shell: Connector menu + header bug_report open the quick issue modal when websiteRegistration is set on cookie GET /api/ereport/access.",
		"routes": []map[string]any{
			{"method": http.MethodGet, "path": "/api/v1/docs", "auth": "none", "summary": "This catalog (public). Fetch first."},
			{"method": http.MethodGet, "path": "/api/v1/ereport/access", "auth": "api_key", "summary": "eReport — check API access.", "requirements": "api + ereport (or admin)."},
			{"method": http.MethodGet, "path": "/api/v1/ereport/orgs", "auth": "api_key", "summary": "eReport — list owned organizations."},
			{"method": http.MethodGet, "path": "/api/v1/ereport/orgs/{orgId}/reports", "auth": "api_key", "summary": "eReport — list reports in one org."},
			{"method": http.MethodGet, "path": "/api/v1/ereport/orgs/{orgId}/reports/{reportId}", "auth": "api_key", "summary": "eReport — read one report (meta + payload + viewUrl)."},
			{"method": http.MethodPost, "path": "/api/v1/ereport/orgs/{orgId}/reports/{reportId}", "auth": "api_key", "summary": "eReport — write after confirmOverwrite:true.", "body": `{"confirmOverwrite":true,"mode":"append|replace","tema":"optional","payload":{}}`},
			{"method": http.MethodPost, "path": "/api/v1/ereport/orgs/{orgId}/reports/{reportId}/sections", "auth": "api_key", "summary": "eReport — create one section (web connector).", "body": `{"title":"…","kind":"funcionalidades|subarticulos","productHistory":"optional concept"}`},
			{"method": http.MethodPatch, "path": "/api/v1/ereport/orgs/{orgId}/reports/{reportId}/sections/{sectionId}", "auth": "api_key", "summary": "eReport — update section title/kind/productHistory.", "body": `{"title":"…","kind":"…","productHistory":"…"}`},
			{"method": http.MethodPost, "path": "/api/v1/ereport/orgs/{orgId}/reports/{reportId}/sections/{sectionId}/groups", "auth": "api_key", "summary": "eReport — create one subsection/group.", "body": `{"title":"…","productHistory":"optional concept"}`},
			{"method": http.MethodPatch, "path": "/api/v1/ereport/orgs/{orgId}/reports/{reportId}/sections/{sectionId}/groups/{groupId}", "auth": "api_key", "summary": "eReport — update group title/productHistory.", "body": `{"title":"…","productHistory":"…"}`},
			{"method": http.MethodPost, "path": "/api/v1/ereport/orgs/{orgId}/reports/{reportId}/sections/{sectionId}/groups/{groupId}/items", "auth": "api_key", "summary": "eReport — create one issue (nombre and/or incidencia; status reprobado). Title-first create allowed; fill incidencia later via PATCH.", "body": `{"nombre":"…","incidencia":"…","status":"reprobado"}`},
			{"method": http.MethodPatch, "path": "/api/v1/ereport/orgs/{orgId}/reports/{reportId}/sections/{sectionId}/groups/{groupId}/items/{itemId}", "auth": "api_key", "summary": "eReport — update issue fields (web connector).", "body": `{"nombre":"…","incidencia":"…","status":"aprobado|reprobado|no_aplica|","solucion":"…","checklist":[…]}`},
			{"method": http.MethodGet, "path": "/api/v1/ereport/library", "auth": "api_key", "summary": "eReport — alias for orgs."},
			{"method": http.MethodGet, "path": "/api/v1/homescool/access", "auth": "api_key", "summary": "Homescool — check API access.", "requirements": "api + homescool (or admin)."},
			{"method": http.MethodGet, "path": "/api/v1/homescool/materials", "auth": "api_key", "summary": "Homescool — list owned study materials (optional ?cycle=1|2|3)."},
			{"method": http.MethodGet, "path": "/api/v1/homescool/materials/{materialId}", "auth": "api_key", "summary": "Homescool — get one material meta + viewUrl."},
			{"method": http.MethodPost, "path": "/api/v1/homescool/materials", "auth": "api_key", "summary": "Homescool — upsert .eoschool JSON (METHOD_V1; confirmOverwrite required).", "body": `{"confirmOverwrite":true,"material":{"format":"eoschool","version":1,"cycle":1,"week":1,"day":1,"level":6,"subject":"mat","title":"…","lesson":{…},"quiz":{…}}}`},
			{"method": http.MethodDelete, "path": "/api/v1/homescool/materials/{materialId}", "auth": "api_key", "summary": "Homescool — delete one owned material (meta + document file)."},
			{"method": http.MethodGet, "path": "/api/v1/epam/access", "auth": "api_key", "summary": "EPAM — check API access.", "requirements": "api + epam (or admin). Legacy pamphlet entitlement accepted."},
			{"method": http.MethodGet, "path": "/api/v1/epam/epams", "auth": "api_key", "summary": "EPAM — list owned documents (meta + viewUrl + articleUrl)."},
			{"method": http.MethodGet, "path": "/api/v1/epam/epams/{id}", "auth": "api_key", "summary": "EPAM — read meta + document + viewUrl + articleUrl."},
			{"method": http.MethodPost, "path": "/api/v1/epam/epams", "auth": "api_key", "summary": "EPAM — create from pamphlet document JSON. Auto-publishes to /articles when configured.", "body": `{"document":{…}} or root pamphlet object`},
			{"method": http.MethodPut, "path": "/api/v1/epam/epams/{id}", "auth": "api_key", "summary": "EPAM — replace document; confirmOverwrite:true required. Auto-publishes.", "body": `{"confirmOverwrite":true,"document":{…}}`},
		},
		"errors": map[string]any{
			"report_storage_missing":         "eReport GET/POST when meta/payload cannot be read.",
			"not_found":                      "Unknown org/material or generic missing resource.",
			"append_existing_item_modified":  "eReport mode append tried to change an existing id.",
			"append_invalid_new_item_status": "eReport mode append new item missing incidencia or status was not reprobado.",
			"replace_confirm_required":       "Homescool POST or eReport replace without confirmOverwrite:true.",
			"website_registration_exists":    "eReport create org/report with purpose website_registration when the owner already has one.",
			"invalid_request":                "Bad material meta or empty html.",
			"unauthorized":                   "Missing/invalid Bearer API key.",
			"forbidden":                      "Missing api and/or product entitlement.",
			"csrf_invalid":                   "Cookie-session CSRF/origin check failed (browser UI).",
			"rate_limited":                   "Over 60 req/min for this key.",
		},
		"payloadSchema": map[string]any{
			"description": "See payloadSchema.ereport and payloadSchema.homescool. Prefer product-specific blocks.",
			"ereport": map[string]any{
				"description":         "Portable Issue Tracker / .ereport JSON under media/ereport/<owner>/.",
				"writeSemantics":      "POST mode append (default) or replace; both need confirmOverwrite:true. Granular section/group/item POST/PATCH mutate one node without append/replace.",
				"postBody":            `{"confirmOverwrite":true,"mode":"append","tema":"optional","payload":{}}`,
				"postBodyReplaceExample": `{"confirmOverwrite":true,"mode":"replace","tema":"Model Checker 1.1","payload":{"appTitle":"Issue Tracker","orgName":"…","reportName":"…","reportDate":"YYYY-MM-DD","reportNumber":"…","theme":"dark","validationCriteria":[],"sections":[]}}`,
				"websiteRegistration": map[string]any{
					"purposeValues": []string{"website_registration", "other"},
					"default":       "other",
					"uniqueness":    "At most one website_registration report per owner on create (HTTP 409 website_registration_exists). Assign-to-site moves the purpose to the chosen report and demotes the previous one to other.",
					"hubCreate":     "Cookie UI POST /api/ereport/orgs (firstReportPurpose) and POST /api/ereport/orgs/{orgId}/reports (purpose).",
					"hubAssign":     "Manage reports → Assign to site / Site defaults → PATCH /api/ereport/orgs/{orgId}/reports/{reportId}/site-connector { assign, sectionId, groupId }.",
					"sessionAccess": "Cookie GET /api/ereport/access returns websiteRegistration: { orgId, reportId, tema, sectionId?, groupId? } | null.",
					"siteConnector": "eduardoos.com (and hosts with the same chrome): main-menu Connector + header bug_report icon are shown only with ereport-connector entitlement AND websiteRegistration binding. They open the quick issue modal locked to that report. Full hub remains product ereport. Without binding, use the eReport hub / local .ereport file (dev reporting).",
					"cliEnv":        "Set EDUARDOOS_ORG_ID and EDUARDOOS_REPORT_ID in .ereport/.env to the website_registration report. API key routes still allow all owned orgs/reports; the site UI is what locks to the binding.",
					"metaFields":    "meta.json purpose + connectorSectionId + connectorGroupId (normalized on load).",
				},
				"webConnector": map[string]any{
					"embedScript": "https://eduardoos.com/ereport/embed.js",
					"embedTheme":  "https://eduardoos.com/ereport/embed-theme.css",
					"advancedModalPath": "/ereport/web-connector",
					"configModalPath":   "/ereport/connector-config",
					"features": []map[string]any{
						{
							"id":          "quick_issue_modal",
							"summary":     "Default site Connector opens a compact modal: list issues in the configured subsection (add-only, no delete), + text input, optimistic local payload update then session POST …/items (120s timeout).",
							"issueParse":  "Text until the first '.' is nombre; remainder is incidencia. No period → whole string is both.",
							"config":      "Gear opens settings; persists sectionId+groupId via PATCH …/site-connector (assign:false) and caches localStorage ereport.connector.defaults. Server meta/access defaults win on open. Advanced editor opens /ereport/web-connector locked.",
							"expressDates": "Create item sets fechaIncidencia (today UTC YYYY-MM-DD if empty) and bumps payload.reportDate + meta.reportDate to that day.",
							"saveAlert":   "window.alert on create/save failure (and advanced editor node saves). Success stays non-blocking in the quick modal.",
						},
						{
							"id":      "header_report_button",
							"summary": "Activity-bar icon (bug_report) left of the menu opener; same visibility gate and opener as the menu Connector entry.",
						},
						{
							"id":      "assign_report_to_site",
							"summary": "Hub Manage reports: Assign to site picks default section/subsection, sets purpose=website_registration, demotes any previous website_registration to other.",
						},
						{
							"id":      "embed_host",
							"summary": "External sites: EduardoOSEreport.mount({ orgId?, reportId?, menuSelector }). Gear Configure opens /ereport/connector-config (session on eduardoos.com) to pick report/section/subsection; stores localStorage ereport.embed.binding.",
						},
						{
							"id":      "host_configure_defaults",
							"summary": "Embed Configure button for hosts without the eReport hub UI; assigns site connector defaults on the signed-in owner's report.",
						},
					},
					"notes": "Auth is cookie session + eReport subscription (no API key in the browser). Session node writes: POST/PATCH /api/ereport/orgs/.../sections|groups|items (use 120s client timeouts). Override --eos-ereport-* for host menu styling.",
				},
				"modes": map[string]any{
					"append":  "Default. Additive merge only. Conservative for agents.",
					"replace": "Full bootstrap/sync. Requires confirmOverwrite:true. Owned reports only.",
					"nodes":   "POST/PATCH .../sections|groups|items — create or edit one node; does not change append/replace.",
				},
				"statusValues":        []string{"", "aprobado", "reprobado", "no_aplica"},
				"appendNewItemStatus": "reprobado only",
				"replaceItemStatus":   "aprobado|reprobado|no_aplica|empty",
				"checklist": map[string]any{
					"description": "Per-issue UX checklist. UI derives display status from checklist completion.",
					"entryFields": map[string]string{
						"id":      "stable checklist row id",
						"label":   "short UX test label (default UX Test)",
						"checked": "boolean — true when the UX check passed",
					},
					"effectiveStatus": "No checklist rows → reprobado. All checked → aprobado. None checked → reprobado. Partial → empty (warning).",
					"legacyHeal":      "On load/save, any item with an empty/missing checklist (except status no_aplica) receives one checked row labeled \"UX cumplidas\" so legacy reports and pre-checklist data stay approved. New UI/API issues are created with an unchecked \"UX Test\" row instead.",
				},
				"effectiveStatus": "Primary: derive from item.checklist (see checklist.effectiveStatus). Stored item.status is kept in sync by the editor.",
				"reportCodeRule":  "reportNumber is the Report Code. Dates fechaIncidencia/fechaSolucion round-trip as YYYY-MM-DD or YYYY-MM-DDTHH:mm.",
				"viewUrlTemplate": "{BASE}/ereport/workspace?user={ownerSafe}&org={orgId}&report={reportId}",
				"rootFields": map[string]string{
					"appTitle": "App title", "orgName": "Organization", "reportName": "Report name",
					"reportDate": "Report date", "reportNumber": "Report code", "theme": "dark|light",
					"validationCriteria": "string[]", "sections": "sections[].groups[].items[]",
				},
				"sectionFields": map[string]string{
					"id": "section id", "title": "title", "kind": "funcionalidades|subarticulos",
					"productHistory": "free-text product / concept history for the section",
					"items": "open issues", "groups": "subsections",
				},
				"groupFields": map[string]string{
					"id": "group id", "title": "title",
					"productHistory": "free-text product / concept history for the group",
					"items": "issues",
				},
				"itemFields": map[string]string{
					"id": "item id", "nombre": "name", "status": "aprobado|reprobado|no_aplica|empty",
					"incidencia": "issue text", "solucion": "resolution", "checklist": "{id,label,checked}[]",
				},
				"metaFields": map[string]string{
					"purpose":             "website_registration|other — site Connector binding when website_registration",
					"connectorSectionId":  "Default main section for the site Connector",
					"connectorGroupId":    "Default subsection for the site Connector",
					"reportDate":          "Report date (YYYY-MM-DD); bumped on express/connector item create",
				},
			},
			"homescool": map[string]any{
				"description":    "METHOD_V1 .eoschool JSON study sheets (US Letter portrait). See skill METHOD_V1.md.",
				"writeSemantics": "POST upserts by cycle+week+day+level+subject. confirmOverwrite:true required. Level 6 only in v1.",
				"postBody":       `{"confirmOverwrite":true,"material":{"format":"eoschool","version":1,"cycle":1,"week":1,"day":1,"level":6,"subject":"mat","locale":"es","title":"Tablas…","lesson":{"kind":"intro","points":[{"id":"p1","heading":"…","body":"…"},{"id":"p2","heading":"…","body":"…"},{"id":"p3","heading":"…","body":"…"}],"summary":"…"},"quiz":{"questionCount":7,"questions":[…]},"media":[]}}`,
				"fields": map[string]string{
					"format": "eoschool", "version": "1", "cycle": "1|2|3", "week": "1–24", "day": "1–3 (pro only d1)",
					"level": "6 (v1)", "subject": "teb|exe|LT|his|geo|art|mat|esp|ing|lat|cie|pro|fin",
					"lesson": "d1 intro; d2/d3 deepen (method v3)", "quiz": "letter quiz on the same sheet (slotSequence)",
				},
				"subjects":        eoschoolSubjects,
				"viewUrlTemplate": "{BASE}/homescool/material?id={materialId}",
				"connector":       "https://github.com/EduardoOsteicoechea/eduardoos-eoschool-connector — clone as .eoschool/",
				"methodDoc":       "/skills/eoschool/METHOD_V1.md",
				"sessionCurriculumProgress": map[string]any{
					"notes": "Browser cookie session + Homescool entitlement (not API key). Default student Elías Osteicoechea (elias-osteicoechea).",
					"routes": []map[string]any{
						{"method": http.MethodGet, "path": "/api/eoschool/curriculum/progress", "auth": "cookie", "summary": "GET progress ?studentKey=", "requirements": "session + homescool"},
						{"method": http.MethodPatch, "path": "/api/eoschool/curriculum/progress/sections", "auth": "cookie+csrf", "summary": "Toggle section done", "body": `{"studentKey":"elias-osteicoechea","dayId":"d1","sectionId":"bib","completed":true}`},
						{"method": http.MethodGet, "path": "/api/eoschool/curriculum/students", "auth": "cookie", "summary": "List students for owner"},
						{"method": http.MethodPost, "path": "/api/homescool/preview", "auth": "cookie+csrf", "summary": "PDF preview from eoschool JSON body"},
					},
				},
			},
			"epam": map[string]any{
				"description":    "Pamphlet / EPAM JSON documents (same shape as the EPAM editor and .epam files).",
				"writeSemantics": "POST creates (auto-publish). PUT replaces with confirmOverwrite:true (auto-publish). No separate publish step.",
				"postBody":       `{"document":{"type":"pamphlet_single_sheet","id":"…","header":{…},"footer":{…},"column_1":[],…}}`,
				"postBodyRoot":   "You may also POST the pamphlet object at the root (with type pamphlet_single_sheet|pamphlet_structured_images).",
				"putBody":        `{"confirmOverwrite":true,"document":{…}}`,
				"viewUrlTemplate":   "{BASE}/documents/pamphlet/open#{epamId}",
				"articleUrlTemplate": "{BASE}/articles/read?id={epamId}",
				"connector":          "https://github.com/EduardoOsteicoechea/epam — clone as .epam/",
				"productId":          productEpam,
				"legacyProductId":    "pamphlet",
			},
		},
	})
}
