package main

import "net/http"

func (a *App) v1DocsHandler(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, map[string]any{
		"version":  "1",
		"title":    "Eduardo OS external API",
		"baseHint": "https://eduardoos.com (or your deployed origin); all paths are absolute from that host",
		"auth": map[string]any{
			"header":    "Authorization",
			"scheme":    "Bearer",
			"keyPrefix": apiKeyPrefix,
			"notes":     "Create keys only in the signed-in UI after subscribing to api. Secret shown once. Never create/revoke keys from external API clients.",
		},
		"rateLimit": map[string]any{
			"requestsPerMinute": apiKeyRatePerMin,
			"onExceed":          "HTTP 429 with Retry-After",
		},
		"entitlements": map[string]any{
			"apiProduct": productAPI,
			"notes":      "Non-admin: active api entitlement plus the product (ereport, homescool, or epam). Legacy entitlement id pamphlet counts as epam. Writes only for resources owned by the key owner.",
		},
		"ownerSafe": "Display metadata only (lowercase email with @ replaced by _at_). Filesystem ownership uses immutable ownerUserId from the API key owner.",
		"keyPolicy": "API keys are created, listed, and revoked only in the Eduardo OS UI. Key lifecycle is not part of the external API.",
		"skills": map[string]any{
			"ereport":   "https://github.com/EduardoOsteicoechea/eduardoos-ereport-connector — clone as .ereport/ sidecar.",
			"homescool": "https://github.com/EduardoOsteicoechea/eduardoos-eoschool-connector — clone as .eoschool/ sidecar. Mirror: https://eduardoos.com/skills/eoschool/",
			"epam":      "https://github.com/EduardoOsteicoechea/epam — clone as .epam/ sidecar. Mirror: https://eduardoos.com/skills/epam/",
		},
		"skill": "https://github.com/EduardoOsteicoechea/eduardoos-ereport-connector — clone as .ereport/. Homescool: eduardoos-eoschool-connector as .eoschool/. EPAM: https://github.com/EduardoOsteicoechea/epam as .epam/.",
		"agentGuidance": "1) Require EDUARDOOS_API_KEY. 2) ALWAYS GET /api/v1/docs first. 3a) eReport: access → orgs → reports → GET → POST. 3b) Homescool materials: access → list → POST with confirmOverwrite. 3c) EPAM: access → POST /api/v1/epam/epams with the pamphlet/.epam document (auto-publishes to /articles when the key owner is the public articles publisher). PUT requires confirmOverwrite:true. 4) Always print viewUrl and articleUrl after write. 5) Never invent endpoints — use this catalog.",
		"routes": []map[string]any{
			{"method": http.MethodGet, "path": "/api/v1/docs", "auth": "none", "summary": "This catalog (public). Fetch first."},
			{"method": http.MethodGet, "path": "/api/v1/ereport/access", "auth": "api_key", "summary": "eReport — check API access.", "requirements": "api + ereport (or admin)."},
			{"method": http.MethodGet, "path": "/api/v1/ereport/orgs", "auth": "api_key", "summary": "eReport — list owned organizations."},
			{"method": http.MethodGet, "path": "/api/v1/ereport/orgs/{orgId}/reports", "auth": "api_key", "summary": "eReport — list reports in one org."},
			{"method": http.MethodGet, "path": "/api/v1/ereport/orgs/{orgId}/reports/{reportId}", "auth": "api_key", "summary": "eReport — read one report (meta + payload + viewUrl)."},
			{"method": http.MethodPost, "path": "/api/v1/ereport/orgs/{orgId}/reports/{reportId}", "auth": "api_key", "summary": "eReport — write after confirmOverwrite:true.", "body": `{"confirmOverwrite":true,"mode":"append|replace","tema":"optional","payload":{}}`},
			{"method": http.MethodGet, "path": "/api/v1/ereport/library", "auth": "api_key", "summary": "eReport — alias for orgs."},
			{"method": http.MethodGet, "path": "/api/v1/homescool/access", "auth": "api_key", "summary": "Homescool — check API access.", "requirements": "api + homescool (or admin)."},
			{"method": http.MethodGet, "path": "/api/v1/homescool/materials", "auth": "api_key", "summary": "Homescool — list owned study materials (optional ?cycle=1|2|3)."},
			{"method": http.MethodGet, "path": "/api/v1/homescool/materials/{materialId}", "auth": "api_key", "summary": "Homescool — get one material meta + viewUrl."},
			{"method": http.MethodPost, "path": "/api/v1/homescool/materials", "auth": "api_key", "summary": "Homescool — upsert material HTML (confirmOverwrite required).", "body": `{"confirmOverwrite":true,"material":{"cycle":3,"week":1,"subject":"idiomas","day":1,"sessionDate":"YYYY-MM-DD","title":"…","slug":"optional","html":"<!DOCTYPE html>…"}}`},
			{"method": http.MethodGet, "path": "/api/v1/epam/access", "auth": "api_key", "summary": "EPAM — check API access.", "requirements": "api + epam (or admin). Legacy pamphlet entitlement accepted."},
			{"method": http.MethodGet, "path": "/api/v1/epam/epams", "auth": "api_key", "summary": "EPAM — list owned documents (meta + viewUrl + articleUrl)."},
			{"method": http.MethodGet, "path": "/api/v1/epam/epams/{id}", "auth": "api_key", "summary": "EPAM — read meta + document + viewUrl + articleUrl."},
			{"method": http.MethodPost, "path": "/api/v1/epam/epams", "auth": "api_key", "summary": "EPAM — create from pamphlet document JSON. Auto-publishes to /articles when configured.", "body": `{"document":{…}} or root pamphlet object`},
			{"method": http.MethodPut, "path": "/api/v1/epam/epams/{id}", "auth": "api_key", "summary": "EPAM — replace document; confirmOverwrite:true required. Auto-publishes.", "body": `{"confirmOverwrite":true,"document":{…}}`},
		},
		"errors": map[string]any{
			"report_storage_missing":         "eReport GET/POST when meta/payload cannot be read.",
			"not_found":                      "Unknown org/material or generic missing resource.",
			"append_existing_item_modified":  "eReport mode append tried to change an existing id.",
			"append_invalid_new_item_status": "eReport mode append new item missing incidencia or status was not reprobado.",
			"replace_confirm_required":       "Homescool POST or eReport replace without confirmOverwrite:true.",
			"invalid_request":                "Bad material meta or empty html.",
			"unauthorized":                   "Missing/invalid Bearer API key.",
			"forbidden":                      "Missing api and/or product entitlement.",
			"rate_limited":                   "Over 60 req/min for this key.",
		},
		"payloadSchema": map[string]any{
			"description": "See payloadSchema.ereport and payloadSchema.homescool. Prefer product-specific blocks.",
			"ereport": map[string]any{
				"description":         "Portable Issue Tracker / .ereport JSON under media/ereport/<owner>/.",
				"writeSemantics":      "POST mode append (default) or replace; both need confirmOverwrite:true.",
				"postBody":            `{"confirmOverwrite":true,"mode":"append","tema":"optional","payload":{}}`,
				"postBodyReplaceExample": `{"confirmOverwrite":true,"mode":"replace","tema":"Model Checker 1.1","payload":{"appTitle":"Issue Tracker","orgName":"…","reportName":"…","reportDate":"YYYY-MM-DD","reportNumber":"…","theme":"dark","validationCriteria":[],"sections":[]}}`,
				"modes": map[string]any{
					"append":  "Default. Additive merge only. Conservative for agents.",
					"replace": "Full bootstrap/sync. Requires confirmOverwrite:true. Owned reports only.",
				},
				"statusValues":        []string{"", "aprobado", "reprobado", "no_aplica"},
				"appendNewItemStatus": "reprobado only",
				"replaceItemStatus":   "aprobado|reprobado|no_aplica|empty",
				"checklist": map[string]any{
					"description": "Per-issue UX checklist. UI derives display status from checklist completion.",
					"entryFields": map[string]string{
						"id":      "stable checklist row id",
						"label":   "short UX test label (default UX Test)",
						"checked": "boolean — true when the UX check passed",
					},
					"effectiveStatus": "No checklist rows → reprobado. All checked → aprobado. None checked → reprobado. Partial → empty (warning).",
					"legacyHeal":      "On load/save, any item with an empty/missing checklist (except status no_aplica) receives one checked row labeled \"UX cumplidas\" so legacy reports and pre-checklist data stay approved. New UI/API issues are created with an unchecked \"UX Test\" row instead.",
				},
				"effectiveStatus": "Primary: derive from item.checklist (see checklist.effectiveStatus). Stored item.status is kept in sync by the editor.",
				"reportCodeRule":  "reportNumber is the Report Code. Dates fechaIncidencia/fechaSolucion round-trip as YYYY-MM-DD or YYYY-MM-DDTHH:mm.",
				"viewUrlTemplate": "{BASE}/ereport/workspace?user={ownerSafe}&org={orgId}&report={reportId}",
				"rootFields": map[string]string{
					"appTitle": "App title", "orgName": "Organization", "reportName": "Report name",
					"reportDate": "Report date", "reportNumber": "Report code", "theme": "dark|light",
					"validationCriteria": "string[]", "sections": "sections[].groups[].items[]",
				},
				"sectionFields": map[string]string{
					"id": "section id", "title": "title", "kind": "funcionalidades|subarticulos",
					"productHistory": "free-text product / concept history for the section",
					"items": "open issues", "groups": "subsections",
				},
				"groupFields": map[string]string{
					"id": "group id", "title": "title",
					"productHistory": "free-text product / concept history for the group",
					"items": "issues",
				},
				"itemFields": map[string]string{
					"id": "item id", "nombre": "name", "status": "aprobado|reprobado|no_aplica|empty",
					"incidencia": "issue text", "solucion": "resolution", "checklist": "{id,label,checked}[]",
				},
			},
			"homescool": map[string]any{
				"description":    "US Letter HTML study sheets under media/homescool/materials/<ownerUserId>/…",
				"writeSemantics": "POST upserts by logical key. confirmOverwrite:true required. Follow eoschool MATERIALS/TEMPLATES.",
				"postBody":       `{"confirmOverwrite":true,"material":{"cycle":3,"week":2,"subject":"locacion/geografia","day":1,"sessionDate":"2026-09-22","title":"Estados y capitales","slug":"geografia-estados-capital","html":"<!DOCTYPE html>…"}}`,
				"fields": map[string]string{
					"cycle": "1|2|3", "week": "1–52", "subject": "path-like lowercase",
					"day": "1–7", "sessionDate": "optional YYYY-MM-DD", "title": "human title",
					"slug": "optional kebab-case", "html": "full HTML document",
				},
				"viewUrlTemplate": "{BASE}/homescool/material?id={materialId}",
				"connector":       "https://github.com/EduardoOsteicoechea/eduardoos-eoschool-connector — clone as .eoschool/",
			},
			"epam": map[string]any{
				"description":    "Pamphlet / EPAM JSON documents (same shape as the EPAM editor and .epam files).",
				"writeSemantics": "POST creates (auto-publish). PUT replaces with confirmOverwrite:true (auto-publish). No separate publish step.",
				"postBody":       `{"document":{"type":"pamphlet_single_sheet","id":"…","header":{…},"footer":{…},"column_1":[],…}}`,
				"postBodyRoot":   "You may also POST the pamphlet object at the root (with type pamphlet_single_sheet|pamphlet_structured_images).",
				"putBody":        `{"confirmOverwrite":true,"document":{…}}`,
				"viewUrlTemplate":   "{BASE}/documents/pamphlet/open#{epamId}",
				"articleUrlTemplate": "{BASE}/articles/read?id={epamId}",
				"connector":          "https://github.com/EduardoOsteicoechea/epam — clone as .epam/",
				"productId":          productEpam,
				"legacyProductId":    "pamphlet",
			},
		},
	})
}
